version: "2"

services:
  voting-app:
    build: ./voting-app/.
    image: jcdemo/voting-app
    ports:
      - "7300:80"
    networks:
      - front-tier
      - back-tier

  result-app:
    build: ./result-app/.
    image: jcdemo/result-app
    ports:
      - "7301:80"
    networks:
      - front-tier
      - back-tier

  worker:
    image: manomarks/worker
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - back-tier

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
